{ pkgs, pkgs-unstable, config, ... }:
{
  environment.systemPackages = [
    pkgs.wget
    pkgs.vim
    pkgs.udiskie
    pkgs.killall
    pkgs.git
    pkgs.alacritty
    pkgs.ghostty
    pkgs.ripgrep
    pkgs.nano
    pkgs.neovim 
    pkgs-unstable.xdg-desktop-portal
    pkgs-unstable.xdg-desktop-portal-gtk
    pkgs-unstable.xdg-desktop-portal-hyprland
    pkgs.tree
    pkgs.yazi
    pkgs.power-profiles-daemon
    pkgs.eza
    pkgs.xfce.thunar
    pkgs.inxi
    pkgs.which
    pkgs.bibata-cursors
    pkgs.lutris
    pkgs.python3
    pkgs.sqlite
    pkgs.starship
    pkgs.oh-my-zsh
    pkgs.helix
    pkgs.greetd
    pkgs.tuigreet
  ];
}
