{ pkgs, pkgs-unstable, config, ... }:
{
  environment.systemPackages = [
    pkgs.wget
    pkgs.vim
    pkgs.udiskie
    pkgs.killall
    pkgs.git
    pkgs.alacritty
    pkgs.ghostty
    pkgs.ripgrep
    pkgs.nano
    pkgs.neovim 
    pkgs.xdg-desktop-portal
    pkgs.xdg-desktop-portal-gtk
    pkgs.xdg-desktop-portal-hyprland
    pkgs.tree
    pkgs.yazi
    pkgs.power-profiles-daemon
    pkgs.eza
    pkgs.xfce.thunar
    pkgs.inxi
    pkgs.which
    pkgs.bibata-cursors
    pkgs.lutris
    pkgs.python3
    pkgs.sqlite
    pkgs.starship
    pkgs.oh-my-zsh
    pkgs.helix
    pkgs.greetd
    pkgs.tuigreet
    pkgs.clang
    pkgs.less
    pkgs-unstable.noctalia-shell
    pkgs.nh
    pkgs.nix-output-monitor
    pkgs.nvd
    pkgs.inotify-tools
    pkgs.wl-clipboard
    pkgs.rofi
    pkgs.librsvg
    pkgs.adwaita-icon-theme
    pkgs.quickshell
    pkgs.cava
    pkgs.pavucontrol
    pkgs.wttrbar
  ];
}
